# Strategy 24 HMP + compcor10 + GSR
# recommend to use high pass of cosine transforms, low pass of nilearn and NO DETREND (according to nilearn recommendations)

# Atlas Configuration
atlas:
  name: "schaefer_2018"
  resolution: 2  # mm (1 or 2)
  n_regions: 200  # Number of brain regions

# Denoising Parameters passed to nifti labels masker 
denoising:
  smoothing_fwhm: 4.0  # mm
  detrend: false
  standardize: null  # options: zscore, zscore_sample, psc, null
  standardize_confounds: true # true false
  low_pass: 0.08  # Hz
  high_pass: null  # Hz
  t_r: null  # nedeed if low and high pass passed and Will be read from BOLD header if null

# Confounds Configuration using nilearn load_confounds
confounds:
  strategy: ["motion", "compcor", "high_pass", "global_signal", "high_pass"]
  motion: "full"
  compcor: "anat_combined"
  n_compcor: 10
  global_signal: "full"
  high_pass: true
  fd_th: null
  dvars_th: null

# Output Configuration
output:
  directory: "./output"
  naming_pattern: "sub-{subject}_ses-{session}_task-{task}_run-{run}_atlas-{atlas_name}-{n_rois}rois.csv"

# BIDS Configuration
bids:
  dataset_path: "/data/Projects/ABIDE2/ABIDEII-BNI_1/derivatives"  # Path to BIDS dataset root (required for BIDS mode)
  task: "rest"  # Task name (e.g., 'rest')
  session: null # if specific session is needed, else - null
  space: "MNI152NLin2009cAsym"  # Space (e.g., 'MNI152NLin2009cAsym')
  extension: "nii.gz" # may be .nii or .nii.gz

# Logging
logging:
  level: "WARNING"  # DEBUG, INFO, WARNING, ERROR
  file: "./logs/denoising.log"